# Generated by Django 5.0.6 on 2024-12-15 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('Creator', models.CharField(max_length=1000, null=True)),
                ('video_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=500)),
                ('pubDateTime', models.CharField(max_length=1000)),
                ('pubTimeZone', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('source_id', models.CharField(max_length=200)),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=100)),
                ('ai_tag', models.CharField(max_length=200)),
                ('sentiment', models.CharField(max_length=200)),
                ('sentiment_stats', models.CharField(max_length=200)),
                ('ai_region', models.CharField(max_length=200)),
                ('ai_org', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200)),
                ('relatedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='webapp.api')),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=200)),
                ('relatedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Country', to='webapp.api')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=200)),
                ('relatedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword', to='webapp.api')),
            ],
        ),
    ]
