# Generated by Django 5.0.6 on 2024-12-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_plansdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('featureOne', models.CharField(max_length=100)),
                ('featureTwos', models.CharField(max_length=100)),
                ('featureThree', models.CharField(max_length=100)),
                ('featureFour', models.CharField(max_length=100)),
                ('featureFive', models.CharField(default='blank', max_length=100)),
                ('featureSix', models.CharField(default='blank', max_length=100)),
                ('featureSeven', models.CharField(default='blank', max_length=100)),
            ],
        ),
    ]
